defmodule MyApp.Repo.Migrations.AddLocation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:locations, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
    end

    create table(:businesses, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
    end
  end

  def down do
    drop table(:businesses)

    drop table(:locations)
  end
end
