defmodule MyApp.Repo.Migrations.AddService do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:services, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
    end
  end

  def down do
    drop table(:services)
  end
end
